### ISSUE TITLE
Crash when typing `/start PlayerWhoDoesNotExist`

### ISSUE THREAD

**Issue by Wuzzy2** [NO411/the_unexpected_gambit#1]
If you type `/start PlayerWhoDoesNotExist`, and `PlayerWhoDoesNotExist` is a player who does not exist, the game crashes.

**Comment by Flederossi** [comment]
Fixed in https://github.com/NO411/the_unexpected_gambit/commit/560bbb83c13e70502193ab2a185ba93674695c8d
