### ISSUE TITLE
Pawn might end up stuck at the end of the board after swap

### ISSUE THREAD

**Issue by Wuzzy2** [NO411/the_unexpected_gambit#2]
When 2 pieces got swapped, a pawn might end up at the end of the board and is stuck there. It can't move nor will it get promoted.

Is this intentional?

**Comment by NO411** [comment]
Is this a problem?

**Comment by andyca111100** [comment]
I guess, because pawn is pretty useless on the last row by itself

**Comment by Wuzzy2** [comment]
Yes, this was my rationale. Unless having a board state with completelely useless pawns IS intended for some reason. :D

**Comment by andyca111100** [comment]
Like, it is possible that the pawn gets swapped back... but still not so good

**Comment by Flederossi** [comment]
Fixed in https://github.com/NO411/the_unexpected_gambit/commit/8b2bb0300967a9e203add0986822866e4f021a62
